version: 2.1
workflows: # 全体の流れを定義
  build_test_and_deploy: # ワークフローの名前
    jobs: # 実行するジョブ(任意の名前)
      - build_and_test

executors: # 各ジョブの初期設定
  working_directory: ~/insta_clone5
  ruby_node_browsers:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: gen
          RAILS_ENV: test

jobs:
  build_and_test:
    executor: ruby_node_browsers
    steps:
      - checkout
      # バンドル キャッシュを復元
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: バンドル インストール
          command: |
            gem install bundler -v 2.2.15
            bundle install
      # バンドル キャッシュを保存
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Yarn の設定
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: Yarn のインストール
          command: yarn install --cache-folder ~/.cache/yarn
      # Yarn のキャッシュを保存
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Rubocopの実行
      - run:
          name: rubocop
          when: always
          command: |
            bundle install
            bundle exec rubocop
      - run:
          name: Create DB
          command: |
            bin/rails db:migrate
            bin/rails db:schema:load --trace
      # テストの実行
      - run:
          name: RSpec
          command: bundle exec rspec
