version: 2.1
orbs:
  ruby-orbs: sue445/ruby-orbs@1.6.0
  heroku: circleci/heroku@1.0.1

workflows: # 全体の流れを定義
  build_test_and_deploy: # ワークフローの名前
    jobs: # 実行するジョブ(任意の名前)
      - build
      - rubocop:
          requires:
            - build
      - rspec:
          requires:
            - build
            - rubocop
      - heroku_deploy:
          requires:
            - build
            - rspec

executors: # 各ジョブの初期設定
  working_directory: ~/insta_clone5
  default:
    docker:
      - image: circleci/ruby:2.7.2-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: gen
          RAILS_ENV: test

jobs:
  build:
    executor: default
    steps:
      # バンドル キャッシュを復元
      - restore_cache:
          keys:
            - rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
            - rails-demo-bundle-v2-
      - run:
          name: バンドル インストール
          command: |
            gem install bundler -v 2.2.15
            bundle install
      # バンドル キャッシュを保存
      - save_cache:
          key: rails-demo-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Yarn の設定
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: Yarnのインストール
          command: yarn install --cache-folder ~/.cache/yarn
      # Yarn のキャッシュを保存
      - save_cache:
          key: rails-demo-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  rubocop:
    executor: default
    steps:
      - run:
          name: rubocopの実行
          command: |
            bundle install
            bundle exec rubocop
  rspec:
    executor: default
    steps:
      - run:
          name: Create DB
          command: |
            bin/rails db:migrate
            bin/rails db:schema:load --trace
      - run:
          name: RSpecの実行
          command: bundle exec rspec
  heroku_deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Deploy to Heroku main
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
